### ISSUE TITLE
PermitActivityActionTypeCode

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#10]
``` xml
<PermitActivityActionTypeCode>[AuthorizeAction].AuthorizeActionType</PermitActivityActionTypeCode>
```

This field is a domain that does not align with the exchange node values. The python does some secondary modifications but they are not good enough.

Most of the wells are `permit not required` or `NR`. The python script put these as empty which isn't acceptable. All of the information I have found does not give us an option for no permit. What should we replace these values with?

**Comment by brigsz** [comment]
Candace is aware of this, we walked through it, and she was beginning to remember the story.  She will research what National Code they decided to use for the `NR`, but as you guess, it will probably be `FR`

**Comment by brigsz** [comment]
If you have a record with `NR` you do not write a record to the AuthorizationAction table.  Wells can be authorized by Rule which does not fit well into the National UIC DB schema.
