### ISSUE TITLE
Phone numbers with extensions

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#12]
### Steps to reproduce

'Telephone Number Text' must be between 0 and 15 characters. You entered 16 characters. 801.266.7100x226 is not valid.

What should we do with extensions or characters over 15?

**Comment by brigsz** [comment]
The desktop solution should allow extensions as DEQ UIC staff often call.  The EPA submission should have the extension stripped out.  The data entry should follow the pattern you have shown above.  We may need to cleanse the database to follow that pattern
