### ISSUE TITLE
Empty Response Detail id

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#13]
### Steps to reproduce

ResponseDetail with the id:  
    R1  
        Response Violation Identifier' should not be empty.  is not valid.

**Comment by steveoh** [comment]
I don't see any enforcement records without a guid. There must be a violation without a response. Check this out next.

**Comment by brigsz** [comment]
I follow thing until you say a "violation without a response" I need to look at some of the data

**Comment by brigsz** [comment]
This is what the client says when asked about violations without responses.

 Do we have violations that do not have responses? That is a problem at the data entry side. We should definitely have responses to violations. This should generate a warning popup or something for the data entry person.

**Comment by steveoh** [comment]
the issue for this is in this facility

```
 # 00:44:28.3698946 Facilities processed 605...
 # 00:44:29.2442850 finding wells for facility: 268bb302-89f2-4baa-a19b-45b3c207
f236...
```
