### ISSUE TITLE
GeologyDetail

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#14]
### Steps to reproduce
1. Run tool
2. submit xml as zip file
3. view summary report
### Expected behaviour

Successful submission
### Actual behaviour

Failed

The Well Geology ID (WellGeologyIdentifier) in the Well record (WellDetail) must map to the Geology ID (GeologyIdentifier) of at least one associated Geology record (GeologyDetail).

Every well has an empty guid for the geology detail because we are not reporting geology details. How should we get around this.

**Comment by brigsz** [comment]
From the Client:
Yep this is when I need to delete all the Geology IDs from the Well table in the Access database before I submit to EPA.  Very clunky, I know.

**Comment by steveoh** [comment]
I don't think that will work for this case. 

`The Well Geology ID (WellGeologyIdentifier) in the Well record (WellDetail) must map to the Geology ID (GeologyIdentifier) of at least one associated Geology record (GeologyDetail).`

It looks like we might need to make one catch all geology record.

**Comment by steveoh** [comment]
well geology id cannot be an empty string as it fails validation.

**Comment by steveoh** [comment]
i made a place holder with `-1` and `Unknown` for the numeric and textual values for a `GeologyDetail` and was able to pass by these errors. If this is ok please give me a 👍

**Comment by brigsz** [comment]
:+1:

**Comment by steveoh** [comment]
I chose a default of `-1` but it wants `0` or `1` as the min value for some of these. Do we ignore the warnings or try to make it happy?

For example

>  The Geology Confining Zone Top (GeologyConfiningZoneTopNumeric) in the Geology record (GeologyDetail) must be an integer in the range 0 < x < 1,000,000. The data will be removed.
> 
> The Geology Injection Zone Permeability Rate (GeologyInjectionZonePermeabilityRateNumeric) in the Geology record (GeologyDetail) must be an integer in the range 0 <= x < 1,000,000. The data will be removed.

**Comment by brigsz** [comment]
Geology warnings are fine.  As DEQ does not submit this data, DEQ is okay getting the warning
