### ISSUE TITLE
Test submission data

### ISSUE THREAD

**Issue by brigsz** [agrc/uic-etl#27]
### export out wells for the following facilities
1. Intrepid Potash
2. Jordan Valley Water Conservancy District
3. Brigham City Corporation

There should be no errors, only warnings during the submission

**Comment by brigsz** [comment]
`FACILITY_ID`  UTEQA19B45B3C207F236 - Intrepid
`FACILITY_ID`  UTEQA49855471FF720C0 - Jordan Valley
`FACILITY_ID`  UTEQ852A643E633D8E66 - Brigham City

Should be able to search the wells table for `FACILITY_ID` and come up with the associated `WELL_ID(s)`

**Comment by keatonwalker** [comment]
The `FACILITY_ID` above doesn't match the format of the `FacilityID` field in the UICFacility feature class. The UICFacility `FacilityID` values all start with UTU

**Comment by keatonwalker** [comment]
Here is a table with wells that belong to all three facilities.

[WellsWithFacilityIds.txt](https://github.com/agrc/uic-etl/files/545390/WellsWithFacilityIds.txt)

**Comment by steveoh** [comment]
Sorry for the goose chase @keatonwalker, @brigsz is out playing in the weeds. I must have given him bad info or something. We needed the guids for those. They are

`"{268BB302-89F2-4BAA-A19B-45B3C207F236}", "{B6BD6456-2607-4172-A498-55471FF720C0}", "{8551FD2F-599C-4BE1-852A-643E633D8E66}"`

**Comment by steveoh** [comment]
[Here is the xml as a text file so I could upload it. UTEQ-10-24-2016.xml.txt](https://github.com/agrc/uic-etl/files/549315/UTEQ-10-24-2016.xml.txt)

No errors or warnings were posted to the spreadsheet log.
