### ISSUE TITLE
FacilityResponseDetail

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#3]
The sample XML has an element called 

``` xml
<FacilityResponseDetail />
```

The Table Field mapping has a section called `Table name: Response`. 

I can't find anything in the UIC SDE. 

What's the story?

**Comment by brigsz** [comment]
Okay, I have an email to Candace asking for some clarification, as there is a Response table in the national database.  I think it goes to the violation table in the Utah UIC database(SDE)
