### ISSUE TITLE
XML submittal from last submission, needs reviewing

### ISSUE THREAD

**Issue by brigsz** [agrc/uic-etl#30]
[SubmitUICData5d6acf8c-7c46-48b7-8034-db3421ddf900.zip](https://github.com/agrc/uic-etl/files/604558/SubmitUICData5d6acf8c-7c46-48b7-8034-db3421ddf900.zip)

**Comment by steveoh** [comment]
i'm running a full export of the uic data. i'll compare the results as is, if the ordering isn't crazy this will be good enough to find errors. Otherwise we will need to build a tool to analyze/compare the xml results.

**Comment by steveoh** [comment]
the order is off for facilities. a cursory glance shows that they do not populate 

#### FacilityDetail

-  `<FacilitySiteTypeCode>`

#### WellDetail

##### Removed

- `<WellTotalDepthNumeric>`
- `<WellGeologyIdentifier>`

##### Wrong

- `<WellStateIdentifier>` is a `{guid}` not `UTEQyada`

#### LocationDetail

- `<LocationIdentifier>` should equal `<WellIdentifier>`
- `<LocationAccuracyValueMeasure>` seems wrong, they have 50 we have 3000 
- lat off by .000004 and long values off by .000010 **i'm going to ignore this**

#### Header needs updating

```xml
<Header xmlns="http://www.exchangenetwork.net/schema/v1.0/ExchangeNetworkDocument.xsd">
        <Author>Candace Cady</Author>
        <Organization>UDEQ</Organization>
        <Title>Data Submittal for UT 1422 UIC Program</Title>
        <CreationTime>2016-11-19T14:33:09</CreationTime>
        <Comment></Comment>        
        <DataService>UIC</DataService>
        <ContactInfo>ccady@utah.gov</ContactInfo>
        <Notification>$notification</Notification>        
        <Sensitivity>Unclasified</Sensitivity>
    </Header>
```

@brigsz It might be worth the effort if we have the money and time to write some code to compare these two xml files. I'll wait for your candle.

**Comment by steveoh** [comment]
<WellTypeDetail>
-        <WellTypeIdentifier>UTEQABAE0C12FE26B9CE</WellTypeIdentifier>
-        <WellTypeCode>5H1</WellTypeCode>
+        <WellTypeIdentifier>UTEQA8C2D80FF6800780</WellTypeIdentifier>
+        <WellTypeCode>5K</WellTypeCode>

double check well type code conversion for this well.

       <WellInspectionDetail>
-        <InspectionIdentifier>UTEQAD2B0FFA0FF29046</InspectionIdentifier>
-        <InspectionAssistanceCode>BH</InspectionAssistanceCode>
+        <InspectionIdentifier>UTEQAD098149886CC280</InspectionIdentifier>
+        <InspectionAssistanceCode>NO</InspectionAssistanceCode>
+        <InspectionDeficiencyCode>NO</InspectionDeficiencyCode>
         <InspectionActionDate>20130206</InspectionActionDate>
+        <InspectionICISComplianceMonitoringReasonCode>U</InspectionICISComplianceMonitoringReasonCode>
+        <InspectionICISComplianceMonitoringTypeCode>U</InspectionICISComplianceMonitoringTypeCode>
+        <InspectionICISComplianceActivityTypeCode>U</InspectionICISComplianceActivityTypeCode>
+        <InspectionICISMOAName>U</InspectionICISMOAName>
+        <InspectionICISRegionalPriorityName>U</InspectionICISRegionalPriorityName>
         <InspectionTypeActionCode>EC</InspectionTypeActionCode>
-        <InspectionWellIdentifier>UTEQ8CCD82D5AA73B43B</InspectionWellIdentifier>
+        <InspectionWellIdentifier>UTEQ80551285E5E8FB74</InspectionWellIdentifier>

Check on AssistanceCode
