### ISSUE TITLE
Incomplete well

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#33]
Well #UTEQA7029FF38E5E1933 is missing it's wellstatus detail and well type detail record.

Investigate why. The child records are probably not valid. Look at why.

**Comment by steveoh** [comment]
This well has no related well operating status. How is the epa getting data for this? I need to run this against the production data or test needs to match prod. @brigsz what do you think?

![image](https://cloud.githubusercontent.com/assets/325813/21209288/d731abd4-c230-11e6-9596-c0fe1ecd02f5.png)

**Comment by brigsz** [comment]
A few fleeting thoughts cross my troubled mind.  

The ID you use is generated during a submission... I wonder if not having the associated items just causes warnings, not actual errors so it is acceptable to EPA.  My other thought is I have heard that filling some of this out can be an iterative process and not always done all at once.......but really, 6 months? so I don't think that is the issue.  I think our best bet is to find the ID from the UIC production DB and give it to Candace to produce the answers for us.  I am sure I can cross walk from the UTEQ id to a UTU one or match the GUID etc.  Is that useful?

**Comment by steveoh** [comment]
Those are all good ideas but they are not useful. Would you crosswalk the access db and let me know where the disconnect is?

**Comment by CanDKD** [comment]
I will check into this.  However, as I was looking at the screen shot above I noticed that the ISCO well was associated with two facilities.  This is a mistake.  I suspect that the association with Weber MS4 is not correct. I will have Brianna correct this.  And, yes, 6 months is too long not to have this sorted out.

**Comment by CanDKD** [comment]
this has been corrected.  the isco wells are not longer assoc with 2 facilities only one.

**Comment by steveoh** [comment]
thanks!
