### ISSUE TITLE
Well operating status

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#35]
### Steps to reproduce
1. Identify Well with guid {A248EBE1-F3C0-4FC9-BD2E-8E689C554A18}
1. Expand the well operating status relationship   
1. View the dates of the records

### Expected behavior
The operating status with the newest operating status date should be used in the xml

### Actual behavior
The 2016/07/13 well was selected over the 2016/8/12 record

Is this because of when the data was submitted? I thought it was long after August that the submission was sent. Is there some other priority on the operating status that I am not aware of other than date? The python script does not provide any clues. It is adding all of the operating status values. The submission xml only has one record. Could this be a bug caused by sending all of the operating status values and not only the newest?

**Comment by CanDKD** [comment]
We send submission to EPA every 6 months so the latest submission should have been sometime after Nov 15.   You gave me dates in two different formats.  Could this be a problem?  The submission should be the latest operating status date.  I am not sure why the python script is adding all op status values.  I will look at this when I get back into the office tomorrow or next week.

**Comment by steveoh** [comment]
Ignore the date formats. I updated the original to make those match. Thank you for looking into this.

**Comment by CanDKD** [comment]
I just subscribed to notifications from this thread.  Sorry I hadn't done
that before :/

**Comment by CanDKD** [comment]
I can not figure this one out.

**Comment by steveoh** [comment]
Maybe it is a bug in how the EPA is handling your Access DB?

**Comment by steveoh** [comment]
i'm going to close this due to inactivity.
