### ISSUE TITLE
Multiple same level contacts

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#37]
When selecting a well contact, the highest quality contact is selected. This is based off of the lowest domain index value. When there are more than one with the same value, is there a way to determine which to choose or does it matter if they are equivalent types?

**Comment by CanDKD** [comment]
The priority goes like this: 1 - Owner/Operator; 2 - Owner; 3 - Operator; 4 - Facility Manager.  If one of these is missing then we have an incomplete data set and that needs to be addressed at our end.  It would be helpful if you could give us a list of those facilities that have duplicate contacts that are causing the problem.

**Comment by steveoh** [comment]
@CanDKD 

There are cases where there are multiple owner/operators (A and B) for a well. I can try to find an example later if necessary but the xml that we got back from your UIC submission has contact B as the contact for facilities or wells in some cases where we have contact A. Both are valid. Is one contact more correct than the other or does it not matter?

**Comment by CanDKD** [comment]
Can you send me a facility id where this problem occurs?  I just talked to Brianna (she does all the data entry) about this.  This may happen when, through time, new owners take over a facility and we didn't delete the old one.

**Comment by steveoh** [comment]
These facilities below have multiple first level contacts

```
{471FA717-B872-4E79-AF39-D26E6A706576} has 2 contacts of type 1,1
{387905F9-C05E-4B56-B485-71A66A4974D7} has 2 contacts of type 7,8,1,1,7
{C457FFC0-AC7A-44A1-A442-DC3380F9EA70} has 2 contacts of type 7,1,1
{DEB13C83-BF84-437B-AC58-BE61A61AD294} has 2 contacts of type 1,1
{7EF7E783-5B09-49D5-9901-AF6D4DF6C4F4} has 2 contacts of type 7,1,1
{7F168CFD-A383-48FF-B6B3-325D6A4F2880} has 2 contacts of type 7,1,1
{1C813242-CC61-4CED-8D7C-E60A972DDF19} has 2 contacts of type 1,1
```

These are only the ones that contain multiple 1's. This does not include the ones that have multiple 2's without a 1 etc.

**Comment by CanDKD** [comment]
Thanks Steve, I'll take a look at them first thing tomorrow morning.

**Comment by CanDKD** [comment]
> {471FA717-B872-4E79-AF39-D26E6A706576} has 2 contacts of type 1,1

Moyes Glass - I changed Lance Moyes Contact Type from Owner/Operator to Owner
> {387905F9-C05E-4B56-B485-71A66A4974D7} has 2 contacts of type 7,8,1,1,7

Hill Air Force Base - changed Mark Roginske Contact Type from Owner/Operator to Official Representative
> {C457FFC0-AC7A-44A1-A442-DC3380F9EA70} has 2 contacts of type 7,1,1

Thermo No. 1 - updated Contacts for this facility, added Plant Manager at Thermo No. 1, may need to delete 2 other contacts - still waiting for response from VP of Business Development
> {DEB13C83-BF84-437B-AC58-BE61A61AD294} has 2 contacts of type 1,1

LS Carson Mink Ranch - changed Chad Fenn Contact Type from Owner/Operator to Owner
> {7EF7E783-5B09-49D5-9901-AF6D4DF6C4F4} has 2 contacts of type 7,1,1

Thermo No. 2 - This facility may not even exist; waiting for response from VP of Business Development
> {7F168CFD-A383-48FF-B6B3-325D6A4F2880} has 2 contacts of type 7,1,1

Thermo No. 4 -  This facility may not even exist; waiting for response from VP of Business Development
> {1C813242-CC61-4CED-8D7C-E60A972DDF19} has 2 contacts of type 1,1

Fillmore KOA - changed Corrine Lewis Contact Type from Owner/Operator to Owner

**Comment by CanDKD** [comment]
All Contacts for Thermo Nos. 1, 2, 4 have been updated.  There are no duplicate contact types.  I have reconciled and posted all changes to production default.
