### ISSUE TITLE
WellContactIdentifier

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#4]
``` xml
 <WellDetail xmlns="http://www.exchangenetwork.net/schema/uic/2">    
    <WellContactIdentifier>MEEP00C02</WellContactIdentifier>
```

The doc says that well contact identifier is the `[Foreign Key]`. There is _no relationship_ between a well and a contact. I was able to find a relationship between a **facility and a contact** but that is a **many to many** relationship. 

How do we put a many to many relationship into a single field? 
or
What is the real value to put into `WellContactIdentifier`?

**Comment by brigsz** [comment]
When you look at "MEEP" in the `WellContactIdentifier` that is the state's primacy code, Utah's is "UTEQ"  by definition positions 1-4 are the primacy code and positions 5-20 are up to the state but must be unique among records, so we have been using the last 15 of the `GUID`, I am confirming if it is the `GUID` or the last 15 of a `foreign key`

**Comment by steveoh** [comment]
@brigsz I figured out that the `ContactType` of a well gives it the priority based on the lowest number. The issue still is that Wells are not related to contacts. Do I use the contacts for the facility since wells and contacts both belong to a facility?
