### ISSUE TITLE
Validation Errors

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#40]
These three wells did not have associated well status records or well type records:
WellDetail Without Matching WellStatusDetail
WellIdentifier
WellStateIdentifier
WellName
UTEQ8C3613540B6DBF04
{2271CA70-13DB-402B-8C36-13540B6DBF04}
EX 7
UTEQAADCA27E861B1A73
{3BA6F592-4ED9-4285-AADC-A27E861B1A73}
StormTech
UTEQA6A4A795DCE1D8F9
{4DFF6D45-F110-4206-A6A4-A795DCE1D8F9}
Storm Water Drainage Well
 
 
WellDetail Without Matching WellTypeDetail
WellIdentifier
WellStateIdentifier
WellName
UTEQ8C3613540B6DBF04
{2271CA70-13DB-402B-8C36-13540B6DBF04}
EX 7
UTEQAADCA27E861B1A73
{3BA6F592-4ED9-4285-AADC-A27E861B1A73}
StormTech
UTEQA6A4A795DCE1D8F9
{4DFF6D45-F110-4206-A6A4-A795DCE1D8F9}
Storm Water Drainage Well
 
These three wells were not included in the data set submitted the 2nd time. The data set in the submission that failed had 3713 well records; the data set in the second submission had 3676 well records. If you would like to me identify the well records that were in the 1st data set but not in the 2nd data set, let me know. I can do that, but maybe not by COB today.
 
This permit record did not have an ownership type code included:
PermitDetail
PermitIdentifier
PermitAORWellNumberNumeric
PermitAuthorizedStatusCode
PermitOwnershipTypeCode
PermitAuthorizedIdentifier
UTEQ8EFD6E2B9A405A85
0.0
RA
UTU49RAA405A85
This permit was not included in the second data set. The first data set had 631 permit records; the second data set had 625 permit records. It looks like it is a rule authorization for the Midtown 360 stormwater wells.
 
There were two enforcement records with the same unique identifier in the data set that failed. Only 1 record with this unique identifier was included in the second data set
Find duplicates for EnforcementDetail
EnforcementIdentifier Field
NumberOfDups
UTEQAD51F0679A55A157
2

**Comment by brigsz** [comment]
Matt,

The incomplete data fields are the type of errors I correct when I do my 'conditioning ' of the database before I submit.  I have asked Brianna to complete the missing datafields when she gets in next week.  The duplicate enforcement record was my fault.  I thought I could include 2 naughty wells under one enforcement record.  I have fixed it (i hope).

**Comment by CanDKD** [comment]
All corrections have been made and reconciled and posted to DEFAULT.

*Candace C. Cady, PG | Underground Injection Control (UIC) Program*
phone:  801.536.4352

office location:    195 North 1950 West, Salt Lake City, Utah  84116
mailing address:  Utah Division of Water Quality
                          PO Box 144870
                          Salt Lake City, Utah   84114

*Emails to and from this email address may be considered public records and
thus subject to Utah GRAMA requirements.*

**Comment by steveoh** [comment]
Those errors seem to have disappeared. Thank you @CanDKD. We have one last validation error from the epa that needs addressing.

![image](https://cloud.githubusercontent.com/assets/325813/23620012/c91b5e66-0252-11e7-9bab-d9dc489a484a.png)

![image](https://cloud.githubusercontent.com/assets/325813/23619956/985a32ac-0252-11e7-8a4d-e35d8c16a096.png)

Can you please look into this record and let me know what is up.

**Comment by CanDKD** [comment]
fixed it.
