### ISSUE TITLE
uic-etl output option

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-etl#42]
I cannot get the -o option for the uic-etl tool to work.

uic-etl.exe –c c:\path\to\db.sde –o c:\path\to\output.xml -v

I have tried this a few times but the output .xml still shows up in the Release directory.  I want it to be written to: c:\GIS\ExchangeNetwork\2017_05_09\UDEQ-5-9-2017.xml  Writing the output to this directory rather than the Release directory will prevent any accidental mucking around of the other files in Release.  Has this option worked for you?

**Comment by CanDKD** [comment]
![command window clip](https://cloud.githubusercontent.com/assets/4369080/25877268/be2ab5c8-34df-11e7-99f0-c725a84529ee.png)

This is what I thought would work.

**Comment by steveoh** [comment]
You are correct, I am not [using the output option](https://github.com/agrc/uic-etl/blob/master/uic-etl/Program.cs#L746) to save the file. I will have to update that to make it do what you want. I am sorry that I overlooked that.

**Comment by CanDKD** [comment]
Can you send me a new zipped file so I can use v1.2.0.  Alternatively, can you tell me what I need to change in version 1.0 so the output option works.  Thanks.
