### ISSUE TITLE
WellGeologyIdentifier

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#5]
``` xml
 <WellDetail xmlns="http://www.exchangenetwork.net/schema/uic/2">    
    <WellGeologydentifier></WellGeologydentifier>
```

The doc says that well geology identifier is the `[Foreign Key]`. There is _no relationship_ between a well and a geology. I was not able to find a geology table.

What goes in this value?

**Comment by brigsz** [comment]
Okay, I need to decipher this email and decide a path forward, but wanted to record this.

> WellContact is the same as the FaciltiyContact. WellGeology - we have not been submitting it as it is not a Required ! field. This information is buried in the VerticalWellEvent field which is complicated. Right now the python script writes a GEOLOGY_ID to the Access DB Well table which I have to wo-manually delete before I submit to EPA - very clunky process!! Entering info in the VerticalWellEvent field requires much manual QA from data editor so not such an ideal situaltion.

**Comment by steveoh** [comment]
🔍 so, I can skip well geology is what I am reading...

**Comment by brigsz** [comment]
I believe so, but I need to understand the last sentence, I will speak with Candace later today.  I think she is saying in the end that the whole geology section is a pain so we don't even deal with it.

**Comment by steveoh** [comment]
Ignoring this as well.
