### ISSUE TITLE
WellTypeDetail

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-etl#6]
There is a section on wells called well type details that is not mentioned in the UIC mapping. Do we skip this block of items?

``` xml
<WellTypeDetail>
            <WellTypeIdentifier>auto incrementing int</WellTypeIdentifier>
            <WellTypeCode>1H</WellTypeCode>
            <WellTypeDate>20020102</WellTypeDate>
            <WellTypeWellIdentifier>MEEP00W01</WellTypeWellIdentifier>
 </WellTypeDetail>
```

**Comment by brigsz** [comment]
I just need to put my thoughts out.  

WellTypeCode is actually UICWell.WellSubClass  but you need to look at the UICWellSubClassDomain, write down the code and then look in the python code to get the the actual value you need. 

How about something like...

``` xml
<WellTypeDetail>
            <WellTypeIdentifier>auto incrementing int</WellTypeIdentifier>
            <WellTypeCode>[UICWell].WellSubClass | UICWellSubClassDomain</WellTypeCode>
            <WellTypeDate>[UICWellOperatingStatus].OperatingStatusDate| yyyMMdd</WellTypeDate>
            <WellTypeWellIdentifier>[UICWell].Guid</WellTypeWellIdentifier>
</WellTypeDetail>
```

Here are a few notes,
Yes you are correct and here's how it works.  Each well can have several records in the UICWell OperatingStatus table.  For example, there can be a record for when the well is proposed to be built, one for when it is under construction, one for when it is active, and one for when it is closed.  Not all wells have multiple records.  But to determine the `Well_Type_Date`, the earliest  date when we first heard anything about a well, the python script has to determine the earliest date.  You would think that the earliest date would correspond to a record that is for 'proposed' but we sometimes first hear about a well when it is already built and active.

There is still one step after that.

**Comment by brigsz** [comment]
So would you like UICWell.WellSubclass.UICWellSubClassDomain?  There is still one step after that.

**Comment by brigsz** [comment]
That would be for xml tag WellTypeCode
